//***************//
// User Requests//
//***************//
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
	"username": "aaaaa",
	"email": "aaaa@handlemanchild.com",
	"firstName": "Angela",
	"lastName": "Merkel",
	"profilePic": "",
	"isAdmin": false,
	"isBanned": false,
	"location": {
		"city": "Berlin",
		"postCode": 11011,
		"country": "Germany"
	}
}

### 
// GET all users
GET http://localhost:5000/api/v1/users/

### 
// GET one user by Id
GET http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4

###
// UPDATE user by Id
PUT http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4
Content-Type: application/json

{
	"location": {
		"city": "Munich",
		"postCode": 81541,
		"country": "Germany"
	}
}

###
// DELETE user by Id
DELETE http://localhost:5000/api/v1/users/62320425f5a24a2024f0ecb9

###
// add event to user's cart
PATCH http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4/cart/6231e8e39f85393d34a594a9
Content-Type: application/json

###
// add event to user's list of eventsAsOrganizer
PATCH http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4/eventsAsOrganizer/6231e8e39f85393d34a594a9
Content-Type: application/json

###
// add event to user's list of eventsAsOrganizer
PATCH http://localhost:5000/api/v1/users/6232032df5a24a2024f0eca0/eventsAsAttendee/6231e8e39f85393d34a594a9
Content-Type: application/json


//***************//
// Event Requests//
//***************//

###
POST http://localhost:5000/api/v1/events
Content-Type: application/json

{
	"eventName": "One Night in Bangkok (in Berlin)",
	"eventDateTime": "2022-03-31T20:00:00",
	"eventLoc": {
		"address": "Freiheit Strasse 1",
		"city": "Berlin",
		"postCode": "11011",
		"country": "Germany"
	},
	"cuisine": "Thai",
	"description": "Good company and good conversation over good Singha beer and authentic southern Thai dishes homecooked by a native Thai",
	"responseDateline": "2022-03-25T20:00:00",
	"contributionAmt": 25,
	"contributionCurrency": "EUR",
	"numOfAttendeesAllowed": 8
}

###
// GET all events
GET http://localhost:5000/api/v1/events

### 
// GET events by city
GET http://localhost:5000/api/v1/events/city/Berlin

### 
// GET events by postal code
GET http://localhost:5000/api/v1/events/postCode/11011

###
// GET event by Id
GET http://localhost:5000/api/v1/events/6231e8e39f85393d34a594a9

###
// UPDATE event by Id
PUT http://localhost:5000/api/v1/events/6231e8e39f85393d34a594a9
Content-Type: application/json

{
	//"eventName": "One Night in Chennai (in Berlin)",
	//"eventDateTime": "2022-03-21T20:00:00",
	//"status": "ongoing" | "cancelled" | "over"
	//"eventLoc": {
	//	"address": "Platz der Republik 1",
	//	"city": "Berlin",
	//	"postCode": "11011",
	//	"country": "Germany"
	//},
	//"cuisine": "South Indian",
	//"description": "Good company and good conversation over good IPA and authentic south Indian dishes homecooked by a native Tamil",
	//"responseDateline": "2022-03-20T20:00:00",
	//"contributionAmt": 30,
	//"contributionCurrency": "EUR"
	//"numOfAttendeesAllowed": 6
	//"numOfAttendeesReg": 1
	"contributionCurrency": "EUR"
}

###
// DELETE event by Id
DELETE http://localhost:5000/api/v1/events/622be8c92c18ed45eca86e91

###
// add review to event
PATCH http://localhost:5000/api/v1/events/6231e8e39f85393d34a594a9/reviews
Content-Type: application/json

{
	"reviewer": "6232032df5a24a2024f0eca0",
	"content": "Donald loves this!",
	"score": 3
}


//*********************//
// Converation Requests//
//*********************//

###
POST http://localhost:5000/api/v1/conversations
Content-Type: application/json

{
	"creator": "62320378f5a24a2024f0eca4",
    "participants": [
		"62320378f5a24a2024f0eca4",
		"623203aff5a24a2024f0eca8",
		"6232032df5a24a2024f0eca0"
	],
    "subject": "Building Access",
    "event": "6231e8e39f85393d34a594a9",
    "messages": [{
		"author": "62320378f5a24a2024f0eca4",
		"content": "Please ring the buzzer when you arrive!"
	}]
}

###
// GET all conversations
GET http://localhost:5000/api/v1/conversations

###
// GET conversation by Id
GET http://localhost:5000/api/v1/conversations/623348a68c11723620a84503

###
// GET all conversations in which a given user Id is a participant
GET http://localhost:5000/api/v1/conversations/participants/623203aff5a24a2024f0eca8

###
// GET all conversations related to an event Id
GET http://localhost:5000/api/v1/conversations/events/6231e8e39f85393d34a594a9

###
// UPDATE - edit a message in a conversation
PUT http://localhost:5000/api/v1/conversations/623349bd8c11723620a84517/messages/623349bd8c11723620a84518
Content-Type: application/json

{
	"content": "Can't wait!"
}

###
// PUT - edit conversation by adding a new message
PUT http://localhost:5000/api/v1/conversations/623348a68c11723620a84503/users/6232032df5a24a2024f0eca0
Content-Type: application/json

{
	"content": "yay!"
}
