//***************//
// User Requests//
//***************//

// POST - create user
POST http://localhost:5000/api/v1/users
Content-Type: application/json

{
	"username": "angelaMer",
	"email": "angie@gmail.com",
	"password": "angelaMer",
	"confirmPassword": "angelaMer",
	"firstName": "Angela",
	"lastName": "Merkel",
	"profilePic": "",
	"isAdmin": false,
	"isBanned": false,
	"location": {
		"city": "Berlin",
		"postCode": 11011,
		"country": "Germany"
	}
}

###
// POST - user login
POST http://localhost:5000/api/v1/users/login
Content-Type: application/json

{
	"email": "angela@gmail.com",
	"password": "angelaMer"
}

### 
// GET all users
GET http://localhost:5000/api/v1/users/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjNhNGE5OGEzZjQ5ODI4NjBiN2I1ODgiLCJlbWFpbCI6ImFuZ2VsYUBnbWFpbC5jb20iLCJpYXQiOjE2NDgyMjE1NzQsImV4cCI6MTY0ODIyNTE3NH0.AZQ5iSUehnQgQGzycHlSkDXmMvSZ8FDlXpI1dDGK96U

### 
// GET one user by Id
GET http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjM1ZWNmNDU0MTAwZjNiNzBjYjNkM2IiLCJlbWFpbCI6InZsYWRpbWlyLnB1dGluQHNvdmlldGdsb3J5LmNvbSIsImlhdCI6MTY0NzczNDgzNiwiZXhwIjoxNjQ3NzM4NDM2fQ.9LmxJWk86sj-4_bUJMs7rtriPno499ZGIMS2YSLKOrc

###
// UPDATE user by Id
PUT http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4
Content-Type: application/json

{
	"location": {
		"city": "Munich",
		"postCode": 81541,
		"country": "Germany"
	}
}

###
// UPDATE user's list of unread convos by removing read convo
PUT http://localhost:5000/api/v1/users/6232032df5a24a2024f0eca0/unreadConversations/623456b97ace55268c5df081
Content-Type: application/json

###
// UPDATE user's cart by removing event
PUT http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4/cart/events/6231e8e39f85393d34a594a9
Content-Type: application/json

###
// UPDATE user's list of eventsAsOrganizer by removing event
PUT http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4/eventsAsOrganizer/events/6231e8e39f85393d34a594a9
Content-Type: application/json

###
// UPDATE user's list of eventsAsAttendee by removing event
PUT http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4/eventsAsAttendee/events/6231e8e39f85393d34a594a9
Content-Type: application/json

###
// DELETE user by Id
DELETE http://localhost:5000/api/v1/users/623a4a98a3f4982860b7b588
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjNhNGE5OGEzZjQ5ODI4NjBiN2I1ODgiLCJlbWFpbCI6ImFuZ2VsYUBnbWFpbC5jb20iLCJpYXQiOjE2NDgyMjE1NzQsImV4cCI6MTY0ODIyNTE3NH0.AZQ5iSUehnQgQGzycHlSkDXmMvSZ8FDlXpI1dDGK96U

###
// add event to user's cart
PATCH http://localhost:5000/api/v1/users/623203aff5a24a2024f0eca8/cart/events/6231e8e39f85393d34a594a9
Content-Type: application/json

###
// add event to user's list of eventsAsOrganizer
PATCH http://localhost:5000/api/v1/users/62320378f5a24a2024f0eca4/eventsAsOrganizer/events/6231e8e39f85393d34a594a9
Content-Type: application/json

###
// add event to user's list of eventsAsOrganizer
PATCH http://localhost:5000/api/v1/users/6232032df5a24a2024f0eca0/eventsAsAttendee/events/6231e8e39f85393d34a594a9
Content-Type: application/json


//***************//
// Event Requests//
//***************//

###
POST http://localhost:5000/api/v1/events
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MjNhNDJkYmRlMTBiMzQxYzhjNGM5MjAiLCJlbWFpbCI6InNpcmlAZ21haWwuY29tIiwiaWF0IjoxNjQ4MDg0MzQ1LCJleHAiOjE2NDgwODc5NDV9.0MolRx4z9zh5BLJtzUTp8zQx5Htz8fcMRtgeL8qu8Tw
Content-Type: application/json

{
	"eventName": "One Night in Barcelona (in Bangkok)",
	"eventDateTime": "2022-04-09T20:00:00",
	"eventLoc": {
		"address": "Yummy Strasse 6",
		"city": "Bangkok",
		"postCode": "10330",
		"country": "Thailand"
	},
	"cuisine": "Spanish",
	"description": "Good company and good conversation over good Spanish wine and authentic Spanish dishes homecooked by a native",
	"responseDateline": "2022-04-05T20:00:00",
	"contributionAmt": 1000,
	"contributionCurrency": "THB",
	"numOfAttendeesAllowed": 6
}

###
// GET all events
GET http://localhost:5000/api/v1/events

###
// GET all events from Heroku server
GET https://supper-club-social-backend.herokuapp.com/api/v1/events

### 
// GET events by city
GET http://localhost:5000/api/v1/events/city/Ber

### 
// GET events by postal code
GET http://localhost:5000/api/v1/events/postCode/11011

###
// GET event by Id
GET http://localhost:5000/api/v1/events/6231e8e39f85393d34a594a9

###
// UPDATE event by Id
PUT http://localhost:5000/api/v1/events/6234a58f4ed7f43c3cf2a8a7
Content-Type: application/json

{
	//"eventName": "One Night in Chennai (in Berlin)",
	//"eventDateTime": "2022-03-21T20:00:00",
	//"status": "ongoing" | "cancelled" | "over"
	//"eventLoc": {
	//	"address": "Platz der Republik 1",
	//	"city": "Berlin",
	//	"postCode": "11011",
	//	"country": "Germany"
	//},
	//"mainPic": "pic URL here"
	//"cuisine": "South Indian",
	//"description": "Good company and good conversation over good IPA and authentic south Indian dishes homecooked by a native Tamil",
	//"responseDateline": "2022-03-20T20:00:00",
	//"contributionAmt": 30,
	//"contributionCurrency": "EUR"
	//"numOfAttendeesAllowed": 6
	"mainPic": "pic URL here"
}

###
// DELETE event by Id
DELETE http://localhost:5000/api/v1/events/622be8c92c18ed45eca86e91

###
// add review to event
PATCH http://localhost:5000/api/v1/events/6231e8e39f85393d34a594a9/reviews
Content-Type: application/json

{
	"reviewer": "6232032df5a24a2024f0eca0",
	"content": "Donald loves this!",
	"score": 3
}


//*********************//
// Converation Requests//
//*********************//

###
POST http://localhost:5000/api/v1/conversations
Content-Type: application/json

{
	"creator": "6232032df5a24a2024f0eca0",
    "participants": [
		"62320378f5a24a2024f0eca4",
		"623203aff5a24a2024f0eca8",
		"6232032df5a24a2024f0eca0"
	],
    "subject": "Beverages",
    "event": "6231e8e39f85393d34a594a9",
    "messages": [{
		"author": "6232032df5a24a2024f0eca0",
		"content": "Too bad you're not serving any American food."
	}]
}

###
// GET all conversations
GET http://localhost:5000/api/v1/conversations

###
// GET conversation by Id
GET http://localhost:5000/api/v1/conversations/623348a68c11723620a84503

###
// GET all conversations in which a given user Id is a participant
GET http://localhost:5000/api/v1/conversations/participants/623203aff5a24a2024f0eca8

###
// GET all conversations related to an event Id
GET http://localhost:5000/api/v1/conversations/events/6231e8e39f85393d34a594a9

###
// UPDATE - edit a message in a conversation
PUT http://localhost:5000/api/v1/conversations/623464154d36142f50303843/users/6232032df5a24a2024f0eca0/messages/623464154d36142f50303844
Content-Type: application/json

{
	"content": "I miss American food."
}

###
// PUT - edit conversation by adding a new message
PUT http://localhost:5000/api/v1/conversations/623464154d36142f50303843/users/6232032df5a24a2024f0eca0
Content-Type: application/json

{
	"content": "yay!"
}

### 
// DELETE conversation by id
DELETE http://localhost:5000/api/v1/conversations/62345dc1c437f92508c85aa5